[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
dotenv = "0.15.0"
itertools = "0.10.5"
reqwest = "0.11.13"
tokio = { version = "1.22.0", features = ["full"] }
